// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/biomarker_result.dart';
import 'models/chat_session.dart';
import 'models/lab_report.dart';
import 'models/patient.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 43374721021634303),
    name: 'BiomarkerResult',
    lastPropertyId: const obx_int.IdUid(16, 557227151494494808),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8311007396144179298),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7003478582146622850),
        name: 'reportId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3379532221307932101),
        relationField: 'report',
        relationTarget: 'LabReport',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8538982661102518196),
        name: 'biomarkerKey',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 1392927204606220163),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5340206100583292618),
        name: 'displayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8728809077050687104),
        name: 'originalName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2898622599170083683),
        name: 'value',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6127582037364476427),
        name: 'valueText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 599283984331863205),
        name: 'unit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4264026709673287210),
        name: 'refLow',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7199065854849004568),
        name: 'refHigh',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5746957425242179671),
        name: 'refRangeRaw',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5390727517074401123),
        name: 'flagIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1992889568151447381),
        name: 'loincCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3517617036688763310),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7180524887398215806),
        name: 'testDate',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(3, 4620355086107760043),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 557227151494494808),
        name: 'embedding',
        type: 28,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8974340425748468029),
    name: 'LabReport',
    lastPropertyId: const obx_int.IdUid(10, 3363130530674385663),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4335555029720643786),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 652891634675757976),
        name: 'patientId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 2507639558608191303),
        relationField: 'patient',
        relationTarget: 'Patient',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8317769571820516631),
        name: 'labName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1399534182947736117),
        name: 'reportDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8067978305039408039),
        name: 'pdfPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8501515813670469083),
        name: 'originalFileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 552261805728786105),
        name: 'importedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4640898689459882170),
        name: 'extractedCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1588133887542722585),
        name: 'totalDetected',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3363130530674385663),
        name: 'rawText',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3215559289155237862),
    name: 'Patient',
    lastPropertyId: const obx_int.IdUid(5, 21552575435671509),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4852877670769733455),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7057969574424133937),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 112067596845685068),
        name: 'dateOfBirth',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 115706620260631781),
        name: 'sex',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 21552575435671509),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 542975154161431803),
    name: 'ChatSession',
    lastPropertyId: const obx_int.IdUid(4, 4126270972844958425),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3079507420252501277),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7755307406885512726),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1585498312990007282),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4126270972844958425),
        name: 'lastMessageAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1397208082251365964),
    name: 'PersistedChatMessage',
    lastPropertyId: const obx_int.IdUid(6, 5450536964930078917),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2957032474519806104),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4019668193248367598),
        name: 'sessionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 2477129363995053950),
        relationField: 'session',
        relationTarget: 'ChatSession',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6374967230335097998),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2972012503306002202),
        name: 'roleIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2296869470696146310),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5450536964930078917),
        name: 'isError',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 1397208082251365964),
    lastIndexId: const obx_int.IdUid(5, 2477129363995053950),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BiomarkerResult: obx_int.EntityDefinition<BiomarkerResult>(
      model: _entities[0],
      toOneRelations: (BiomarkerResult object) => [object.report],
      toManyRelations: (BiomarkerResult object) => {},
      getId: (BiomarkerResult object) => object.id,
      setId: (BiomarkerResult object, int id) {
        object.id = id;
      },
      objectToFB: (BiomarkerResult object, fb.Builder fbb) {
        final biomarkerKeyOffset = fbb.writeString(object.biomarkerKey);
        final displayNameOffset = fbb.writeString(object.displayName);
        final originalNameOffset = object.originalName == null
            ? null
            : fbb.writeString(object.originalName!);
        final valueTextOffset = object.valueText == null
            ? null
            : fbb.writeString(object.valueText!);
        final unitOffset = object.unit == null
            ? null
            : fbb.writeString(object.unit!);
        final refRangeRawOffset = object.refRangeRaw == null
            ? null
            : fbb.writeString(object.refRangeRaw!);
        final loincCodeOffset = object.loincCode == null
            ? null
            : fbb.writeString(object.loincCode!);
        final categoryOffset = object.category == null
            ? null
            : fbb.writeString(object.category!);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.report.targetId);
        fbb.addOffset(2, biomarkerKeyOffset);
        fbb.addOffset(3, displayNameOffset);
        fbb.addOffset(4, originalNameOffset);
        fbb.addFloat64(5, object.value);
        fbb.addOffset(6, valueTextOffset);
        fbb.addOffset(7, unitOffset);
        fbb.addFloat64(8, object.refLow);
        fbb.addFloat64(9, object.refHigh);
        fbb.addOffset(10, refRangeRawOffset);
        fbb.addInt64(11, object.flagIndex);
        fbb.addOffset(12, loincCodeOffset);
        fbb.addOffset(13, categoryOffset);
        fbb.addInt64(14, object.testDate.millisecondsSinceEpoch);
        fbb.addOffset(15, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final biomarkerKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final displayNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final originalNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final valueParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final valueTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final unitParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final refLowParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final refHighParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final refRangeRawParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final flagIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final loincCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final testDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0),
        );
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final object = BiomarkerResult(
          id: idParam,
          biomarkerKey: biomarkerKeyParam,
          displayName: displayNameParam,
          originalName: originalNameParam,
          value: valueParam,
          valueText: valueTextParam,
          unit: unitParam,
          refLow: refLowParam,
          refHigh: refHighParam,
          refRangeRaw: refRangeRawParam,
          flagIndex: flagIndexParam,
          loincCode: loincCodeParam,
          category: categoryParam,
          testDate: testDateParam,
          embedding: embeddingParam,
        );
        object.report.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.report.attach(store);
        return object;
      },
    ),
    LabReport: obx_int.EntityDefinition<LabReport>(
      model: _entities[1],
      toOneRelations: (LabReport object) => [object.patient],
      toManyRelations: (LabReport object) => {},
      getId: (LabReport object) => object.id,
      setId: (LabReport object, int id) {
        object.id = id;
      },
      objectToFB: (LabReport object, fb.Builder fbb) {
        final labNameOffset = object.labName == null
            ? null
            : fbb.writeString(object.labName!);
        final pdfPathOffset = fbb.writeString(object.pdfPath);
        final originalFileNameOffset = object.originalFileName == null
            ? null
            : fbb.writeString(object.originalFileName!);
        final rawTextOffset = object.rawText == null
            ? null
            : fbb.writeString(object.rawText!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.patient.targetId);
        fbb.addOffset(2, labNameOffset);
        fbb.addInt64(3, object.reportDate.millisecondsSinceEpoch);
        fbb.addOffset(4, pdfPathOffset);
        fbb.addOffset(5, originalFileNameOffset);
        fbb.addInt64(6, object.importedAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.extractedCount);
        fbb.addInt64(8, object.totalDetected);
        fbb.addOffset(9, rawTextOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final labNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final reportDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final pdfPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final originalFileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final importedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final extractedCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final totalDetectedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final rawTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = LabReport(
          id: idParam,
          labName: labNameParam,
          reportDate: reportDateParam,
          pdfPath: pdfPathParam,
          originalFileName: originalFileNameParam,
          importedAt: importedAtParam,
          extractedCount: extractedCountParam,
          totalDetected: totalDetectedParam,
          rawText: rawTextParam,
        );
        object.patient.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.patient.attach(store);
        return object;
      },
    ),
    Patient: obx_int.EntityDefinition<Patient>(
      model: _entities[2],
      toOneRelations: (Patient object) => [],
      toManyRelations: (Patient object) => {},
      getId: (Patient object) => object.id,
      setId: (Patient object, int id) {
        object.id = id;
      },
      objectToFB: (Patient object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final sexOffset = object.sex == null
            ? null
            : fbb.writeString(object.sex!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.dateOfBirth?.millisecondsSinceEpoch);
        fbb.addOffset(3, sexOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateOfBirthValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dateOfBirthParam = dateOfBirthValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dateOfBirthValue);
        final sexParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = Patient(
          id: idParam,
          name: nameParam,
          dateOfBirth: dateOfBirthParam,
          sex: sexParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    ChatSession: obx_int.EntityDefinition<ChatSession>(
      model: _entities[3],
      toOneRelations: (ChatSession object) => [],
      toManyRelations: (ChatSession object) => {},
      getId: (ChatSession object) => object.id,
      setId: (ChatSession object, int id) {
        object.id = id;
      },
      objectToFB: (ChatSession object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.lastMessageAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final lastMessageAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = ChatSession(
          id: idParam,
          title: titleParam,
          createdAt: createdAtParam,
          lastMessageAt: lastMessageAtParam,
        );

        return object;
      },
    ),
    PersistedChatMessage: obx_int.EntityDefinition<PersistedChatMessage>(
      model: _entities[4],
      toOneRelations: (PersistedChatMessage object) => [object.session],
      toManyRelations: (PersistedChatMessage object) => {},
      getId: (PersistedChatMessage object) => object.id,
      setId: (PersistedChatMessage object, int id) {
        object.id = id;
      },
      objectToFB: (PersistedChatMessage object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.session.targetId);
        fbb.addOffset(2, contentOffset);
        fbb.addInt64(3, object.roleIndex);
        fbb.addInt64(4, object.timestamp.millisecondsSinceEpoch);
        fbb.addBool(5, object.isError);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final roleIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isErrorParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = PersistedChatMessage(
          id: idParam,
          content: contentParam,
          roleIndex: roleIndexParam,
          timestamp: timestampParam,
          isError: isErrorParam,
        );
        object.session.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.session.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BiomarkerResult] entity fields to define ObjectBox queries.
class BiomarkerResult_ {
  /// See [BiomarkerResult.id].
  static final id = obx.QueryIntegerProperty<BiomarkerResult>(
    _entities[0].properties[0],
  );

  /// See [BiomarkerResult.report].
  static final report = obx.QueryRelationToOne<BiomarkerResult, LabReport>(
    _entities[0].properties[1],
  );

  /// See [BiomarkerResult.biomarkerKey].
  static final biomarkerKey = obx.QueryStringProperty<BiomarkerResult>(
    _entities[0].properties[2],
  );

  /// See [BiomarkerResult.displayName].
  static final displayName = obx.QueryStringProperty<BiomarkerResult>(
    _entities[0].properties[3],
  );

  /// See [BiomarkerResult.originalName].
  static final originalName = obx.QueryStringProperty<BiomarkerResult>(
    _entities[0].properties[4],
  );

  /// See [BiomarkerResult.value].
  static final value = obx.QueryDoubleProperty<BiomarkerResult>(
    _entities[0].properties[5],
  );

  /// See [BiomarkerResult.valueText].
  static final valueText = obx.QueryStringProperty<BiomarkerResult>(
    _entities[0].properties[6],
  );

  /// See [BiomarkerResult.unit].
  static final unit = obx.QueryStringProperty<BiomarkerResult>(
    _entities[0].properties[7],
  );

  /// See [BiomarkerResult.refLow].
  static final refLow = obx.QueryDoubleProperty<BiomarkerResult>(
    _entities[0].properties[8],
  );

  /// See [BiomarkerResult.refHigh].
  static final refHigh = obx.QueryDoubleProperty<BiomarkerResult>(
    _entities[0].properties[9],
  );

  /// See [BiomarkerResult.refRangeRaw].
  static final refRangeRaw = obx.QueryStringProperty<BiomarkerResult>(
    _entities[0].properties[10],
  );

  /// See [BiomarkerResult.flagIndex].
  static final flagIndex = obx.QueryIntegerProperty<BiomarkerResult>(
    _entities[0].properties[11],
  );

  /// See [BiomarkerResult.loincCode].
  static final loincCode = obx.QueryStringProperty<BiomarkerResult>(
    _entities[0].properties[12],
  );

  /// See [BiomarkerResult.category].
  static final category = obx.QueryStringProperty<BiomarkerResult>(
    _entities[0].properties[13],
  );

  /// See [BiomarkerResult.testDate].
  static final testDate = obx.QueryDateProperty<BiomarkerResult>(
    _entities[0].properties[14],
  );

  /// See [BiomarkerResult.embedding].
  static final embedding = obx.QueryDoubleVectorProperty<BiomarkerResult>(
    _entities[0].properties[15],
  );
}

/// [LabReport] entity fields to define ObjectBox queries.
class LabReport_ {
  /// See [LabReport.id].
  static final id = obx.QueryIntegerProperty<LabReport>(
    _entities[1].properties[0],
  );

  /// See [LabReport.patient].
  static final patient = obx.QueryRelationToOne<LabReport, Patient>(
    _entities[1].properties[1],
  );

  /// See [LabReport.labName].
  static final labName = obx.QueryStringProperty<LabReport>(
    _entities[1].properties[2],
  );

  /// See [LabReport.reportDate].
  static final reportDate = obx.QueryDateProperty<LabReport>(
    _entities[1].properties[3],
  );

  /// See [LabReport.pdfPath].
  static final pdfPath = obx.QueryStringProperty<LabReport>(
    _entities[1].properties[4],
  );

  /// See [LabReport.originalFileName].
  static final originalFileName = obx.QueryStringProperty<LabReport>(
    _entities[1].properties[5],
  );

  /// See [LabReport.importedAt].
  static final importedAt = obx.QueryDateProperty<LabReport>(
    _entities[1].properties[6],
  );

  /// See [LabReport.extractedCount].
  static final extractedCount = obx.QueryIntegerProperty<LabReport>(
    _entities[1].properties[7],
  );

  /// See [LabReport.totalDetected].
  static final totalDetected = obx.QueryIntegerProperty<LabReport>(
    _entities[1].properties[8],
  );

  /// See [LabReport.rawText].
  static final rawText = obx.QueryStringProperty<LabReport>(
    _entities[1].properties[9],
  );
}

/// [Patient] entity fields to define ObjectBox queries.
class Patient_ {
  /// See [Patient.id].
  static final id = obx.QueryIntegerProperty<Patient>(
    _entities[2].properties[0],
  );

  /// See [Patient.name].
  static final name = obx.QueryStringProperty<Patient>(
    _entities[2].properties[1],
  );

  /// See [Patient.dateOfBirth].
  static final dateOfBirth = obx.QueryDateProperty<Patient>(
    _entities[2].properties[2],
  );

  /// See [Patient.sex].
  static final sex = obx.QueryStringProperty<Patient>(
    _entities[2].properties[3],
  );

  /// See [Patient.createdAt].
  static final createdAt = obx.QueryDateProperty<Patient>(
    _entities[2].properties[4],
  );
}

/// [ChatSession] entity fields to define ObjectBox queries.
class ChatSession_ {
  /// See [ChatSession.id].
  static final id = obx.QueryIntegerProperty<ChatSession>(
    _entities[3].properties[0],
  );

  /// See [ChatSession.title].
  static final title = obx.QueryStringProperty<ChatSession>(
    _entities[3].properties[1],
  );

  /// See [ChatSession.createdAt].
  static final createdAt = obx.QueryDateProperty<ChatSession>(
    _entities[3].properties[2],
  );

  /// See [ChatSession.lastMessageAt].
  static final lastMessageAt = obx.QueryDateProperty<ChatSession>(
    _entities[3].properties[3],
  );
}

/// [PersistedChatMessage] entity fields to define ObjectBox queries.
class PersistedChatMessage_ {
  /// See [PersistedChatMessage.id].
  static final id = obx.QueryIntegerProperty<PersistedChatMessage>(
    _entities[4].properties[0],
  );

  /// See [PersistedChatMessage.session].
  static final session =
      obx.QueryRelationToOne<PersistedChatMessage, ChatSession>(
        _entities[4].properties[1],
      );

  /// See [PersistedChatMessage.content].
  static final content = obx.QueryStringProperty<PersistedChatMessage>(
    _entities[4].properties[2],
  );

  /// See [PersistedChatMessage.roleIndex].
  static final roleIndex = obx.QueryIntegerProperty<PersistedChatMessage>(
    _entities[4].properties[3],
  );

  /// See [PersistedChatMessage.timestamp].
  static final timestamp = obx.QueryDateProperty<PersistedChatMessage>(
    _entities[4].properties[4],
  );

  /// See [PersistedChatMessage.isError].
  static final isError = obx.QueryBooleanProperty<PersistedChatMessage>(
    _entities[4].properties[5],
  );
}
