#!/usr/bin/env sh

files=$(git diff --cached --name-only --diff-filter=ACMR -- '*.dart')

if [ -z "$files" ]; then
  exit 0
fi

echo "Formatting staged Dart files..."
dart format $files
git add $files
